server:
  port: 8080

spring:
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-account-changelog.xml
    default_schema: ${DB_SCHEMA:account}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:5432/skillbox
    username: ${DB_USERNAME:account}
    password: ${DB_PASSWORD:account}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${DB_SCHEMA:account}
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    consumer:
      group-id: ${KAFKA_GROUP_ID:app.1}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  topic:
    account: ${KAFKA_TOPIC:topic-account}

